remote_theme: pages-themes/cayman@v0.2.0
title: Andrew Brown ePortfolio
description: SNHU CS499 - Computer Science Capstone
github:
  is_project_page: true
show_downloads: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
